version: "3.6"
services:
  himanshu-portfolio:
    build:
      context: $PWD/../..
      dockerfile: $PWD/himanshu-portfolio/Dockerfile
    restart: always
    expose:
      - "80"
      - "443"
    environment:
      - VIRTUAL_HOST=himanshu-pahuja.com, www.himanshu-pahuja.com
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=himanshu-pahuja.com, www.himanshu-pahuja.com
      - LETSENCRYPT_EMAIL=0xhimanshupahuja@gmail.com
  nginx:
    image: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    expose:
      - 80
    depends_on:
      - himanshu-portfolio
    links:
      - himanshu-portfolio

networks:
  default:
    external:
      name: nginx-proxy